ARG VERSION=10
ARG IMAGE=rockylinux/rockylinux
FROM ${IMAGE}:${VERSION} AS updater

# Update all packages and clean up
RUN dnf update -y && \
    dnf clean all && \
    rm -rf /var/cache/dnf

# Copy updated system to scratch
FROM scratch
COPY --from=updater / /
CMD ["/bin/bash"]
